### ISSUE TITLE
CreateTable

### ISSUE THREAD

**Issue by Lu1sAndr3sR** [cuboalcub/RCP#19]

**Comment by Lu1sAndr3sR** [comment]
**Mockup**

![5](https://github.com/user-attachments/assets/8bf1b15c-578c-40b1-be2d-ec2926cd2c71)

**Activities**
- [ ] Crear Service
- [x] Realizar tabla de ingreso de datos
- [x] Crear botón  "Agregar actividad"
- [x] Crear botón "Eliminar actividad"
- [x] Crear botón "Guardar"
- [x] Crear Objeto en la carpeta **models/actividad**

**Comment by cuboalcub** [comment]
Error: 
El error es a la hora de selecionar varios precedentes, intentar areglar eso
